version: '2'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx_conf:/etc/nginx/conf.d
      - ./data/nginx_vhost:/etc/nginx/vhost.d
      - ./data/nginx_html:/usr/share/nginx/html
      - ./data/nginx_certs:/etc/nginx/certs:ro

#      - ./conf/gitea.conf:/etc/nginx/conf.d/gitea.conf:ro
#      - ./conf/youtrack.conf:/etc/nginx/conf.d/youtrack.conf:ro
#      - ./conf/drone.conf:/etc/nginx/conf.d/drone.conf:ro

    network_mode: bridge

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    restart: always

    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./conf/nginx.conf:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen=true'
    network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always

    volumes_from:
      - nginx-proxy
    volumes:
      - ./data/nginx_certs:/etc/nginx/certs:rw
      - ./data/nginx_acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - docker-gen

    network_mode: bridge
